// src/data.jsx — loads real data from data.json (generated by sync/sync_excel.py)
// Sets window.SalesData when ready; notifies listeners via window.onSalesDataReady().

(function () {
  "use strict";

  window.SalesData        = null;
  window._sdReady         = false;
  window._sdError         = null;
  window._sdCallbacks     = [];

  window.onSalesDataReady = function (cb) {
    if (window._sdReady) { cb(window.SalesData); }
    else                  { window._sdCallbacks.push(cb); }
  };

  function fire(data) {
    window.SalesData    = data;
    window._sdReady     = true;
    window._sdCallbacks.forEach(function (cb) { cb(data); });
    window._sdCallbacks = [];
  }

  // -----------------------------------------------------------------
  // Helper functions — closed over the dynamically loaded data
  // -----------------------------------------------------------------
  function buildHelpers(raw) {
    var TEAMS        = raw.TEAMS;
    var SALESPEOPLE  = raw.SALESPEOPLE;
    var WEEKS        = raw.WEEKS;
    var ACTIVITY     = raw.ACTIVITY;
    var STAGES       = raw.STAGES;
    var CUSTOMERS    = raw.CUSTOMERS;
    var generated_at = raw.generated_at || "";

    function pickVal(cell, ctype) {
      if (!cell) return 0;
      if (ctype === "existing") return cell.existing || 0;
      if (ctype === "new")      return cell.new      || 0;
      return cell.total || 0;
    }

    function totalForTeam(teamId, weekIdx, field, ctype) {
      ctype = ctype || "all";
      var sps = teamId === "all"
        ? SALESPEOPLE
        : SALESPEOPLE.filter(function (s) { return s.team === teamId; });
      return sps.reduce(function (sum, sp) {
        var spWeeks = ACTIVITY[sp.id];
        if (!spWeeks || weekIdx >= spWeeks.length) return sum;
        return sum + pickVal(spWeeks[weekIdx][field], ctype);
      }, 0);
    }

    function weeklyTotals(teamId, field, ctype) {
      ctype = ctype || "all";
      return WEEKS.map(function (_, wi) {
        return totalForTeam(teamId, wi, field, ctype);
      });
    }

    function teamConversionRate(teamId, ctype) {
      ctype = ctype || "all";
      var sps = teamId === "all"
        ? SALESPEOPLE
        : SALESPEOPLE.filter(function (s) { return s.team === teamId; });
      var totalQuotes = 0, totalWon = 0;
      sps.forEach(function (sp) {
        (ACTIVITY[sp.id] || []).forEach(function (w) {
          totalQuotes += pickVal(w.quotations, ctype);
          totalWon    += pickVal(w.newClients, ctype);
        });
      });
      return totalQuotes ? Math.round((totalWon / totalQuotes) * 100) : 0;
    }

    function personConversionRate(spId, ctype) {
      ctype = ctype || "all";
      var totalQuotes = 0, totalWon = 0;
      (ACTIVITY[spId] || []).forEach(function (w) {
        totalQuotes += pickVal(w.quotations, ctype);
        totalWon    += pickVal(w.newClients, ctype);
      });
      return totalQuotes ? Math.round((totalWon / totalQuotes) * 100) : 0;
    }

    function customerCount(teamId) {
      return teamId === "all"
        ? CUSTOMERS.length
        : CUSTOMERS.filter(function (c) { return c.team === teamId; }).length;
    }

    function isStale(customer) {
      return customer.daysSinceFirstContact > 90
        && !["won", "lost"].includes(customer.stage);
    }

    return {
      TEAMS, SALESPEOPLE, WEEKS, ACTIVITY, STAGES, CUSTOMERS, generated_at,
      MARKET: raw.MARKET || null,
      totalForTeam, weeklyTotals, teamConversionRate, personConversionRate,
      customerCount, pickVal, isStale,
    };
  }

  // -----------------------------------------------------------------
  // Fetch data.json  (cache-busted so Wednesday refresh is immediate)
  // -----------------------------------------------------------------
  fetch("data.json?_=" + Date.now())
    .then(function (r) {
      if (!r.ok) throw new Error(
        "data.json not found (" + r.status + "). Run: python sync\\sync_excel.py"
      );
      return r.json();
    })
    .then(function (raw) {
      fire(buildHelpers(raw));
    })
    .catch(function (err) {
      console.error("[SalesData]", err.message);
      window._sdError = err.message;
      fire(null);
    });
})();
